version: "3.8"
services:
  apm-website:
    image: nginx:alpine
    container_name: apm-website
    # Порты наружу можно даже не прокидывать, 
    # Cloudflare подключится к nginx напрямую через внутреннюю сеть Docker!
    volumes:
      - ./docs:/usr/share/nginx/html:ro
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run
    environment:
      # Сюда нужно будет вставить токен, который выдаст Cloudflare
      - TUNNEL_TOKEN=ТВОЙ_ТОКЕН
    restart: unless-stopped
